# Site settings
title: willekaputra
email: willekaputra@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Developer & BJJ Addict
url: "http://willekaputra.github.io" # the base hostname & protocol for your site
github_username:  willekaputra

# Build settings
markdown: kramdown
theme: jekyll-theme-slate